### ISSUE TITLE
Need more space for aggregation pipelines

### ISSUE THREAD

**Issue by jeetendra-choudhary** [mingo-app/mingo#326]
When editing aggregation pipelines it becomes really difficult to navigate to start of pipeline and then scroll back down or bottom of pipeline, it would be really helpful if the completed pipeline or the initial pipeline can be minimised and provide the available space to the pipeline which is in progress, something like this GitHub editor.

![Screenshot 2022-01-10 at 12 37 57 PM](https://user-images.githubusercontent.com/19362419/148729038-6d2e09cf-392e-4c2a-b85c-84dcdea0ccb9.png)

This is the reference screenshot for problem I am facing.

![Screenshot 2022-01-10 at 12 34 35 PM](https://user-images.githubusercontent.com/19362419/148728734-8a68e251-5e25-4da0-a39b-09b9ba741ae7.png)

**Comment by tothradoslav** [comment]
Hi, thanks for the feedback!

We have increased the size of the input a bit as a quick solution. We will have to come up with a better way to handle input height because of the limitations of the editor we used. 

I will keep this issue open and will let you know when it's improved. Meanwhile, the box size increase will be available in the next release (a couple of days from now).

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by jeetendra-choudhary** [comment]
Thanks for the update, however I still do not see the space increased, it would be better if the working stage can be starched  and the one we are not working could be shirked by user something like this -
![Screenshot 2022-03-16 at 10 31 01 AM](https://user-images.githubusercontent.com/19362419/158520255-8a29f102-6efa-4d08-b3a3-aa02083f1ca7.png)

This screen shot is taken fro latest RC Release and still not much space :(

![Screenshot 2022-03-16 at 10 34 40 AM](https://user-images.githubusercontent.com/19362419/158520348-69e9650b-75fc-4432-8ee9-a4a938a36eb4.png)

I hope I am not asking too much, I love the software and would like to use it.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
