### ISSUE TITLE
An Error Occurred during Compare and Sync

### ISSUE THREAD

**Issue by chandanamalliah** [mingo-app/mingo#444]
![Error - Compare and Sync](https://user-images.githubusercontent.com/108456809/176628257-a4880186-01fe-4e75-9db9-9ebf68c331d5.png)

Hello!
Am facing issue while using the Compare and Sync- Getting "An Error Occured". Please help to check on the issue. 
as well, typos in the word "Occured" :)

**Comment by TechMky** [comment]
I was wondering if there's a log message somewhere, where its visible as what the error was. This is completely ambiguous as to what the error was.

**Comment by chandanamalliah** [comment]
> Hi @chandanamalliah , could you please provide some details?
> 
> 1. version of Mingo you are using - 1.8.1
> 2. your operating system - Windows 10 Enterprise
> 3. is your connection just a simple one or do you use SSH, SSL / TSL?- Yes simple connection. Using port-forward to connect the db in openshit 
> 
> Thinking of the most efficient way to debug this for you. I have very little data :)

**Comment by tothradoslav** [comment]
We are now working on this issue, as we found that this could happen with special setups, such as your port-forwarding, VPN or SSH. The problem is, that for almost everything, mingo uses regular mongodb drivers. But in case of compare/sync, we are using real a real "mongo" command as you would in terminal (command line). This could result in such errors. Could you @chandanamalliah please let me know if the issue also happens when you are using a simple / non-port-forwarded connection. Thanks!

**Comment by achtan** [comment]
this issue could be caused by MongoDB v6, but we need to verify this first.

@TechMky @chandanamalliah are you using v6 or v5?

**Comment by talalus** [comment]
I had the same error on MongoDB v6 locally
`
Build Info: {
    "version": "6.0.3",
    "gitVersion": "f803681c3ae19817d31958965850193de067c516",
    "modules": [],
    "allocator": "system",
    "environment": {
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
`

**Comment by chandanamalliah** [comment]
> We are now working on this issue, as we found that this could happen with special setups, such as your port-forwarding, VPN or SSH. The problem is, that for almost everything, mingo uses regular mongodb drivers. But in case of compare/sync, we are using real a real "mongo" command as you would in terminal (command line). This could result in such errors. Could you @chandanamalliah please let me know if the issue also happens when you are using a simple / non-port-forwarded connection. Thanks!

Thanks for your response. I was using port-forward to connect our mongodb instance as its not available in on-prem. We were dependent on Mingo for the DB migration, which is already completed and mingo tool is no longer used for us.

**Comment by ismaelheinen** [comment]
Hi, I've been having issues with Sync for a few weeks now, I think it's similar to this thread.

1. Pop!_OS 22.04 LTS
2. mongod v6.0.3
3. mingo v1.11

I tested both in .deb version and appimage.
I even cleared all mingo cache etc when reinstalling

The problem is the same, all collections quickly report: An error Occurred. During the execution of: Compare selected collections

**Comment by tothradoslav** [comment]
Hi, this was related to the mongod v6 and will be corrected for the next release. Thank you

**Comment by tothradoslav** [comment]
This has been corrected in the last version. Please let us know if it is OK.

https://github.com/mingo-app/mingo/releases/tag/v1.12.0

**Comment by ismaelheinen** [comment]
here version 1.12.1 linux .deb and appimage also, still not working.



![image](https://user-images.githubusercontent.com/45688790/234387953-3b5992fd-3f2e-41c5-96c8-14a0db3969b2.png)
