### ISSUE TITLE
Connection error to self-hosted MongoDB via VPN

### ISSUE THREAD

**Issue by mippeqf** [mingo-app/mingo#482]
Copied the connection URI directly from NoSQLBooster, which works fine with the same configuration. 

Testing the connection on Mingo returns 
```Unable to connect to this connection:

MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
```
and no further information.

**Comment by tothradoslav** [comment]
Thank you for this. Since this is a security issue, you can't provide much more information, I guess, so we'll have to come up with a way for me to be able to reproduce or at lease imitate the problem. I'm personally using Mingo in the same configuration (self-hosted mongodb over VPN) and it works fine. Could you tell me more about the type of VPN used?

**Comment by TheLD6978** [comment]
Maybe I can shed some light on this. Setup is as follows:

Wireguard VPN with custom DNS set to an internal Resolver.
The server mongoDB runs on is assigned a DNS record like mongo.internal.example.com.
This entry is also used to connect to the mongo server inside mingo.

The mongoDB server itself (and i think thats the real problem here) is running in a docker container configured as a single node replica set. The container is named "mongo" and the replica set member list therefore contains only one node with hostname "mongo".

I suspect mingo assumes the it can reach all nodes inside the replica set member list via the hostnames listed there and thats not the case in this setup.

I hope this is enough information to reproduce the issue.

**Comment by tothradoslav** [comment]
Hi, sorry for the late reply :( but have you tried this on the latest version of Mingo? Many changes have been made since and this could have been resolved. Thanks.

**Comment by TheLD6978** [comment]
Just tested with latest mingo client 1.13.3 and the error persists. Its also easy to reproduce locally using docker: 

```
docker run --rm -tip 27017:27017 --hostname steve --init --name mongo mongo bash -c "set -m; mongod --replSet rs0 --bind_ip_all & sleep 10; mongosh --eval 
'rs.initiate()'; fg 1;"
```

This starts a local mongo server with hostname `steve` and initializes a single node replica set after 10 seconds. If you now connect to `mongodb://localhost/` in mingo, it shows the following error: 

```
Unable to connect to this connection:

MongoServerSelectionError: getaddrinfo ENOTFOUND steve
```

**Comment by FichteFoll** [comment]
I am not able to connect to any mongo database, either hosted locally via docker or when connecting through a VPN. I exported the URIs from Studio 3T, which handles both of these fine.
The errors I receive are 
```
MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb
```
even though my remote connection is specified via an IPv4. Mingo always verifying all connections is also a bit annoying because I don't have my local database running at all times.

I am using Arch Linux and mingo 1.13.5.
