### ISSUE TITLE
Not all databases can be loaded in Mingo

### ISSUE THREAD

**Issue by responsible-chris** [mingo-app/mingo#533]
**Describe the bug**
This is hard one, not sure how you can reproduce it.  We have databases hosted at mongodb.com.

I recently updated my connection to prod (which has sufficient permissions) and its failing to find any of the collections that exist in the database (confirmation through other tools and the fact oiur app is running means they are there.

I have reinstalled mingo, deleted all the configuration for it so i had to reload my license and other values from scratch.

Our various staging, test, developer clusters load the DBs just fine.  Production is much larger, is it possible there is a timeout somewhere getting all the collection data?

Our Dev

**Screenshots**
PRODUCTION:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/101907490/214907131-877d2f12-b7db-4a66-bef8-b33cc564a2a5.png">
STAGING:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/101907490/214908199-73f7c1cc-0e83-4517-9236-24d3fb191c82.png">

**Desktop (please complete the following information):**
 - Mingo version: 1.10.1
 - OS:Monterey 12.6.1
 -

**Comment by responsible-chris** [comment]
Additional note: The reason I deleted the working connection configuration originally and tried to re add it (and found that now it woudn't work anymore), was that it was never seeing new Collections being added to my database.

So it seems like it had been failing to refresh the collection list from this one database for many many months.  I only noticed when I went to investigate a new collection and it wasn't in the list and nothing would cause the list to be updated to reflect new collections

**Comment by tothradoslav** [comment]
Thank you. How many collections are in that database? It is possible, that there was a timeout and it could not be handled. 

The first thing you could try is go to settings (preferences) and set the "Default connection timeout" to let's say an hour. See if it works.

Mingo loads some meta data about the collections, too. This may be causing your issue.

I have just now actually optimized certain actions and seem to be much faster now. Let's see if it was actually a timeout issue.

**Comment by responsible-chris** [comment]
HI @tothradoslav thanks for the reply.  I tried setting the time out higher and it didn't have any effect.  When I click the "refresh" button in the UI it spins for about 25 seconds before coming back with no changes.

The number o collections isn't to big (120?), but some do have millions of records

**Comment by tothradoslav** [comment]
Thanks for the info. I have changed the caching mechanism and we'll see if this helps your usecase. In my case (about 70 collections) it works much much faster now.

**Comment by responsible-chris** [comment]
@tothradoslav Great! do you. know when those changes will get released?  

Thanks

**Comment by tothradoslav** [comment]
definitely in next release, so in about 2 weeks, but an RC will be available sooner and I'll let you know

**Comment by tothradoslav** [comment]
This has been corrected in the last version. Please let us know if it is OK. Sorry, a bit late ... :(

https://github.com/mingo-app/mingo/releases/tag/v1.12.0

**Comment by reinerlee** [comment]
![image](https://user-images.githubusercontent.com/1051902/230538742-929b0f2b-00a6-4e3d-9ec5-8bab4b6c9a6c.png)


Hi @tothradoslav , the problem is still persisted in v1.12.0

**Comment by responsible-chris** [comment]
Yes I am still seeing the issue.  For smaller Collections it runs for 10+ seconds and then shows the list of collections.

However for our big DB it returns right away with 0 collections found

**Comment by sagrawal31** [comment]
This is also happening to me. The snapshot of the production database (on a separate dev environment) loads fine, but the production database itself does not. The spinner keeps spinning but nothing happens. Tried everything. Deleting the connection/project etc.

![image](https://user-images.githubusercontent.com/1804514/233013016-5ab933b2-668e-4d56-8457-2c7bbe320136.png)

**Comment by sagrawal31** [comment]
It started to work after some time. I think that is because Mingo is trying to build metadata on a large dataset.

**Comment by tothradoslav** [comment]
In the last version 1.12.1, we changed the way the metadata are loaded. But we will definitely work on this issue with large number of collections.

**Comment by tothradoslav** [comment]
In case of large databases (100+ collections) we removed the background functionality to load meta data completely. If you want to see such details, go to "Collections & Stats" in database context menu and you can force it to load.

**Comment by tothradoslav** [comment]
Could you please try if this works OK in the latest patch? Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.12.2
