### ISSUE TITLE
Not possible to create new relations

### ISSUE THREAD

**Issue by tcastelli** [mingo-app/mingo#618]
Hello, I am trying to create a new data relation from the UI, but I don't get any response after clicking Save (it looks like the click event is not being triggered). If I click on **_delete_** the expected popups shows, clicking **_cancel_** or **_manage connections_** closes the modal and goes back as expected, but Save click is just being ignored. Not sure how can I give you more information about what is happening underneath.
(I've tried seting up data relations pointing directly to a field called "name" inside the other collection and also with name being under a nested level (management.name) and in both cases I see the same behavior)
![image](https://github.com/mingo-app/mingo/assets/3498481/5e029154-79ce-42fe-ab9f-0fdb8fc668c1)

**Comment by tothradoslav** [comment]
I think i found the problem, let's see in next release. Thanks.

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.

**Comment by ashish-gaikwaad** [comment]
I am still facing this issue in the latest version of **Apple silicon chip** package.
In my case, I have multiple connections. I can create data relations in one connection but am not able to create them in other connections.

Version
![image](https://github.com/user-attachments/assets/5d909717-2aad-43ff-92b8-7ef1501111ee)
