### ISSUE TITLE
Bug: Unable to type

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#67]
The bug that happened in the query field earlier where I couldn't type happened again. This time in the edit value popup field.
Blinking cursor was invisible. Any alphanumeric key did not work at all. Backspace, delete did work.

**Comment by Christilut** [comment]
I can reproduce it by going to a tab that's readonly, then changing it to "unlock in this tab" and then try to edit a field.

**Comment by Christilut** [comment]
Bug that is maybe related: in an unlocked tab, if I click to edit a value, add some text and press cancel. Then edit the value again and the last input still there. I cancelled so I expect the value to be reset.

**Comment by tothradoslav** [comment]
I addressed the "edit value staying as before cancel" issue, will be in next release. 

However, the "unable to type" I can't reproduce. Maybe it's a specific windows issue. Let's see if the above bug was really related.

Did you have this issue in the simple "text input" and in the "more complex" editor (such as when editing entire document) ?  Just trying to rule out / confirm  issues with the ACE editor we are using.

Thanks!

**Comment by Christilut** [comment]
It happens in both.

I just reproduced it by unlocking a tab, then it acted as it should, locking again and unlocking immediately.. could not type

**Comment by Christilut** [comment]
Just downloaded the new version of today.

Still happens but I've noticed that if I alt-tab to a different program and back, I can type.

**Comment by tothradoslav** [comment]
Any news on this?

**Comment by Christilut** [comment]
Still happens although I've seen it less. Had it in the document edit popup yesterday. Haven't been able to reproduce it. I'll check with devtools next time I see it.

I'm working with an unlocked database mostly now, I think that's why it doesn't happen to me anymore.

**Comment by Christilut** [comment]
Just had it again. I kept changing the unlock/lock database to get rid of it but couldn't. Had to restart Mingo and then I could type again.

**Comment by tothradoslav** [comment]
Hi, could you try our latest RC 1.7.0 to see if this still happens? There's also an M1 version for macs, if this is your case.

https://github.com/mingo-app/mingo/releases/tag/v1.7.0-rc1
